# Generated by Django 5.2.7 on 2025-10-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ref_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
