# Generated by Django 5.2.7 on 2025-10-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.customer'),
        ),
    ]
