# Generated by Django 5.2.7 on 2025-10-26 06:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_items_alter_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_receivable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
    ]
